version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.6
        environment:
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

      - restore_cache:
          key: ruby-jet

      - run:
          name: Bundle Install
          command: bundle install

      - save_cache:
          key: ruby-jet
          paths:
            - vendor/bundle

      - run:
          name: RSpec tests
          command: rspec
